[package]
name = "advent-of-code-2020-rust"
version = "0.1.0"
authors = ["Charley DAVID <hello@calyh.re>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
